### ISSUE TITLE
Print logs (stream) live instead of one batch 

### ISSUE THREAD

**Issue by lorenz369** [MarvinWeitz/dockerfile-kernel#13]
When using e.g. the %install magic, it will take several seconds until the user receives feedback from the kernel, as the responses are currently stacked in one list, that is returned after completion of the whole operation.

**Comment by MarvinWeitz** [comment]
Implemented [here](https://github.com/dokempf/dockerfile-kernel/commit/acd6ca79603e701fc8f517c3164e7bd41fad6662)
