### ISSUE TITLE
Limit the line length when executing install magic

### ISSUE THREAD

**Issue by MarvinWeitz** [MarvinWeitz/dockerfile-kernel#35]
The replace cell code of the `install` magic is quite long at this time. Add line breaks to limit the length of these commands.

**Comment by lorenz369** [comment]
Implemented [here](https://github.com/dokempf/dockerfile-kernel/commit/40de1fc9a694e5b7db71bd672afb05ecc310b466)

**Comment by lorenz369** [comment]
Research and fix commands for conda, pip, npm

**Comment by lorenz369** [comment]
Update set_layout with .format("lb" = "ln")
