### ISSUE TITLE
dockstring incomplete

### ISSUE THREAD

**Issue by lorenz369** [MarvinWeitz/dockerfile-kernel#6]
[In this line](https://github.com/MarvinWeitz/dockerfile-kernel/blob/64d2bff4d54aa4093a3e1152096b6e4f92a49689/docker_kernel/magics.py#LL33C1-L33C1) the function `call_magic` misses documentation of  `args`.

**Comment by MarvinWeitz** [comment]
[Fixed](https://github.com/MarvinWeitz/dockerfile-kernel/commit/89e7812696da9cf275420e0c3836222b2b169021)
